version: '3.8'

services:
  restau-map:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restau-map-vibe
    ports:
      - "0.0.0.0:3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
